---
title: Gender Recognition by Voice - project team
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidyverse)
library(ggplot2)
library(patchwork)
```



## 1. Data-preprocessing

```{r}
voices <- read_csv("voice.csv")
head(voices)
```


```{r}
#create dummy variable
voices$label1 <- ifelse(voices$label == "male", 1 , 0) 
#remove column label
voices <- subset(voices, select = -label) 
head(voices)

```

```{r}
#plot meanfreq and Q25 
p1 <-   ggplot(voices, aes(x = meanfreq, y = label1)) + 
    geom_point(alpha = 0.15) +
    geom_smooth(method = "glm", method.args = list(family = "binomial"), se=F)  + theme_bw() +
    labs(y = "gender")
p2 <-   ggplot(voices, aes(x = Q25, y = label1)) + 
    geom_point(alpha = 0.15) +
    geom_smooth(method = "glm", method.args = list(family = "binomial"), se=F)  + theme_bw() + 
    labs(y = "gender")
p1+p2
```

```{r}
p3 <-   ggplot(voices, aes(x = sd, y = label1)) + 
    geom_point(alpha = 0.15) +
    geom_smooth(method = "glm", method.args = list(family = "binomial"), se=F)  + theme_bw() +
    labs(y = "gender")
p4 <-   ggplot(voices, aes(x = sp.ent, y = label1)) + 
    geom_point(alpha = 0.15) +
    geom_smooth(method = "glm", method.args = list(family = "binomial"), se=F)  + theme_bw() + 
    labs(y = "gender")
p3+p4
```


```{r}
#plot meanfun
ggplot(voices, aes(x = meanfun, y = label1)) +
  geom_point(alpha = 0.15) +
  geom_smooth(method = "glm", method.args = list(family = "binomial"), se=F)  + theme_bw() +
  labs(y = "gender")
```





```{r}
#split data into 80% training and 20% test

set.seed(12)
n <- nrow(voices)
index_train <- sample(1:n, round(0.8*n))
voices_train <- voices[index_train, ]
voices_test <- voices[-index_train, ]
dim(voices)
dim(voices_train)
dim(voices_test)
```


## 2. fiting model and Predict 

### a. Full model

```{r}
glm_fullmodel <- glm(label1 ~ ., data = voices_train, family = "binomial")
summary(glm_fullmodel)
```


```{r}
#predict
pred <- predict(glm_fullmodel, newdata = voices_test, type = "response")
pred <- ifelse(pred > 0.5, 1, 0)
confusion_matrix <- table(prediction = pred, actual = voices_test$label1)
addmargins(confusion_matrix)
```

```{r}
#accuracy
(322 + 294)/634
```



### b. Backwards stepwise selection 

```{r}
library(MASS)
step.model <- step(glm_fullmodel, trace = F)
coef(step.model)
```

```{r}
summary(step.model)
```

```{r}
#AIC
glm_Q25 <- glm(label1 ~ Q25, data = voices_train, family = "binomial")
glm_Q75 <- glm(label1 ~ Q75, data = voices_train, family = "binomial")
glm_kurt <- glm(label1 ~ kurt, data = voices_train, family = "binomial")
glm_sp.ent <- glm(label1 ~ sp.ent, data = voices_train, family = "binomial")
glm_sfm <- glm(label1 ~ sfm, data = voices_train, family = "binomial")
glm_meanfun <- glm(label1 ~ meanfun, data = voices_train, family = "binomial")
glm_minfun <- glm(label1 ~ minfun, data = voices_train, family = "binomial")
glm_modindx <- glm(label1 ~ modindx, data = voices_train, family = "binomial")
AIC1 <- AIC(glm_Q25, glm_Q75, glm_kurt, glm_sp.ent, glm_sfm, glm_meanfun, glm_minfun, glm_modindx)
AIC1[order(AIC1$AIC),]
```

```{r}
library(faraway)
round(vif(step.model), 2)
```


```{r}
#predict
pred2 <- predict(step.model, newdata = voices_test, type = "response")
pred2 <- ifelse(pred2 > 0.5, 1, 0)
confusion_matrix <- table(prediction = pred2, actual = voices_test$label1)
addmargins(confusion_matrix)
```

```{r}
#accuracy
(323 + 295)/634
```

### c. RandomForest


```{r}
#randomForest

library(randomForest)
library(rpart)
library(vip)
library(nnet)

voices_train$label1 <- as.factor(voices_train$label1)
voices_test$label1 <- as.factor(voices_test$label1)

rf_model <- randomForest(label1 ~ ., data = voices_train, importance = TRUE)
vip(rf_model, num_features = 21, geom = "point", include_type = TRUE)
```
```{r}
rf_model
```


```{r}
saveRDS(rf_model, "RandomForestmodel.rds")
```


```{r}
#predict
pred3 <- predict(rf_model, newdata = voices_test)
confusion_matrix <- table(prediction = pred3, actual = voices_test$label1)
addmargins(confusion_matrix)
```

```{r}
#accuracy
(324 + 298)/634
```





